### ISSUE TITLE
Logistics Pipes integration - mass storage being detected as full

### ISSUE THREAD

**Issue by hfga** [GregTech6/gregtech6#100]
When connecting a mass storage to a logistics pipes network - at least when using ItemSink modules in a logistics chassis, the mass storage is detected as full and no items are placed in it, even when it can accept more items.

I am not sure if this is something that Gregtech can fix or if is an issue that would need to be dealt with by logistics pipes, but if there is a way to make logistics pipes detect the available space in a mass storage, that would be greatly appreciated. Thank you.

**Comment by GregoriusT** [comment]
Good question, I dont use Logistics Pipes myself, and I heard others talk about being able to use them with my Mass Storages. Have you tried any other ways to insert Items using Logistics Pipes?

**Comment by hfga** [comment]
I have done some further testing and found something quite interesting. First, this only happens with the module in a chassis, the basic logistics pipe (pipe equivalent) works just fine. But even with the module, at first it works fine as well, but as soon as a smaller fraction is introduced (e.g. small pile), the item on the mass storage itself (in this case, regular sulfur dust) stops being directed to it, but every other can do, so it worked with small piles, tiny, piles, 1/72nd piles and even blocks, but the dust themselves stopped being directed there after that. There is a difference with these two pipes, the basic one can interact on all sides, but the chassis is limited to one single side, so I am guessing that if the item itself is redirected to another side of the block and the fractions enter on the side directly connected to the pipe or something like that, that might be causing this issue.

**Comment by GregoriusT** [comment]
My Mass Storages are incredibly basic when it comes to Item interactions, only 2 slots, one slot is empty and can accept all the sizes of dust, and one slot contains a huge size ItemStack of up to a Million, and anything can take from it.

And the Input Slot will instantly transfer its content to the Storage Slot, so not even 1 tick passes for it to happen, meaning it cant be caused by 2 different items trying to enter at the same time.

Is the Sulfur Dust unificated or is it some Sulfur Dust that is not GTs target?

**Comment by hfga** [comment]
The sulfur is all GT6 except for the small pile, which is Sulphur powder from Botany. I've redone the tests using rose gold dust since they are all from GregTech but got the same results, after inserting a fraction, I can put blocks and any fraction in, but the space for whole dusts isn't detected. I have tried doing the same with small piles instead of whole piles and this time the small piles got rejected. So every accepted item gets routed to the mass storage except for the main one in it

**Comment by GregoriusT** [comment]
OH I SEE WHAT MIGHT HAVE HAPPENED THERE!

Logistics Pipes TRY to insert into the second Slot even though the first Slot is where it SHOULD go... Yeah I dont think I can fix that...

**Comment by hfga** [comment]
It seems that this fraction of a tick during which the items are in the first slot is causing the second slot to be selected for the item, as even when inserting 4 small piles to form a new dust this happens. I _guess_ if there were two input slots this wouldn't happen, but it'd probably be too much trouble to change that for a single mod that has a problem with it. Anyway, thank you for taking a look

**Comment by GregoriusT** [comment]
No, that cant be because its not even in that Slot, that Slot is always empty, its that it always picks exactly that one Item that is in the OUTPUT slot to try add its stuff to even if there is no space or allowance for it, waaaaait how much dust does your mass storage contain? is it less than 64?

**Comment by hfga** [comment]
I did have more than 64. While testing with less than 64 I found something interesting that I hadn't, while less than 128, the problem doesn't happen at all, it is only starting at the 129th, even if they are in the same stack, the items up to 128 will go in, and the ones after that will pop out of the pipes. Not sure what that may imply

**Comment by GregoriusT** [comment]
Damnit, LogisticsPipes is truncating stacksizes to a signed byte, which in turn causes something to fuck up on their end...

Yeah I cant really fix that Issue then, I guess...
