### ISSUE TITLE
In Smelting Crucible, Everything Disappears when Something Boiled 

### ISSUE THREAD

**Issue by kuzuanpa** [GregTech6/gregtech6#101]
just like the title,both happens in big and small crucible.
there is a short video shows that.

https://user-images.githubusercontent.com/61902985/211978358-4ebbc5dc-4f8b-4657-83aa-e20d754ee08e.mp4

**Comment by tyrael93** [comment]
I'm not sure if what's happening might be related to the fact you're nbt editing the process instead of heating the material, can't you just use a dense solid tantalum hafnium carbide burning box to heat stuff very fast to test instead?

**Comment by kuzuanpa** [comment]
whether NBT edit or heating it using burning box ,it may not affect anything.
I discovered the bug because I lost my ~300 Unit steel+iron by accidentally throw my fire starter into big steel crucible :-(

**Comment by GregoriusT** [comment]
Uh shit... I looked through my Code to see if there is an obvious Error, but there isn't... And ofcourse I went into my Test World and tried what you did and the same thing happened to me...

Well, here is the Code, I hope someone might be able to spot the Error there, because I sure as heck cant find it...

		List<OreDictMaterialStack> tToBeAdded = new ArrayListNoNulls<>();
		for (int i = 0; i < mContent.size(); i++) {
			OreDictMaterialStack tMaterial = mContent.get(i);
			if (tMaterial == null || tMaterial.mMaterial == MT.NULL || tMaterial.mMaterial == MT.Air || tMaterial.mAmount <= 0) {
				GarbageGT.trash(mContent.remove(i--));
			} else if (tMaterial.mMaterial.mGramPerCubicCentimeter <= WEIGHT_AIR_G_PER_CUBIC_CENTIMETER) {
				GarbageGT.trash(mContent.remove(i--));
				UT.Sounds.send(SFX.MC_FIZZ, this);
			} else if (mTemperature >= tMaterial.mMaterial.mBoilingPoint || (mTemperature > C + 40 && tMaterial.mMaterial.contains(TD.Properties.FLAMMABLE) && !tMaterial.mMaterial.containsAny(TD.Properties.UNBURNABLE, TD.Processing.MELTING))) {
				GarbageGT.trash(mContent.remove(i--));
				UT.Sounds.send(SFX.MC_FIZZ, this);
				if (tMaterial.mMaterial.mBoilingPoint >=  320) try {for (EntityLivingBase tLiving : (List<EntityLivingBase>)worldObj.getEntitiesWithinAABB(EntityLivingBase.class, box(-GAS_RANGE, -1, -GAS_RANGE, GAS_RANGE+1, GAS_RANGE+1, GAS_RANGE+1))) UT.Entities.applyTemperatureDamage(tLiving, tMaterial.mMaterial.mBoilingPoint, 4);} catch(Throwable e) {e.printStackTrace(ERR);}
				if (tMaterial.mMaterial.mBoilingPoint >= 2000) for (int j = 0, k = Math.max(1, UT.Code.bindInt((9 * tMaterial.mAmount) / U)); j < k; j++) WD.fire(worldObj, xCoord-FLAME_RANGE+rng(2*FLAME_RANGE+1), yCoord-1+rng(2+FLAME_RANGE), zCoord-FLAME_RANGE+rng(2*FLAME_RANGE+1), rng(3) != 0);
				if (tMaterial.mMaterial.contains(TD.Properties.EXPLOSIVE)) explode(UT.Code.scale(tMaterial.mAmount, MAX_AMOUNT, 8, F));
				return;
			} else if (!mAcidProof && tMaterial.mMaterial.contains(TD.Properties.ACID)) {
				GarbageGT.trash(mContent.remove(i--));
				UT.Sounds.send(SFX.MC_FIZZ, this);
				setToAir();
				return;
			} else if (mTemperature >= tMaterial.mMaterial.mMeltingPoint && (oTemperature <  tMaterial.mMaterial.mMeltingPoint || tNewContent)) {
				mContent.remove(i--);
				OM.stack(tMaterial.mMaterial.mTargetSmelting.mMaterial, UT.Code.units_(tMaterial.mAmount, U, tMaterial.mMaterial.mTargetSmelting.mAmount, F)).addToList(tToBeAdded);
			} else if (mTemperature <  tMaterial.mMaterial.mMeltingPoint && (oTemperature >= tMaterial.mMaterial.mMeltingPoint || tNewContent)) {
				mContent.remove(i--);
				OM.stack(tMaterial.mMaterial.mTargetSolidifying.mMaterial, UT.Code.units_(tMaterial.mAmount, U, tMaterial.mMaterial.mTargetSolidifying.mAmount, F)).addToList(tToBeAdded);
			}
		}
		for (int i = 0; i < tToBeAdded.size(); i++) {
			OreDictMaterialStack tMaterial = tToBeAdded.get(i);
			if (tMaterial == null || tMaterial.mMaterial == MT.NULL || tMaterial.mMaterial == MT.Air || tMaterial.mAmount <= 0) {
				GarbageGT.trash(tToBeAdded.remove(i--));
			} else {
				tMaterial.addToList(mContent);
			}
		}

**Comment by tyrael93** [comment]
Odd. And worrying.

**Comment by GregoriusT** [comment]
Yeah and it is not even deleted through normal means, as in the Tungsten does not show up in the Ender Garbage List. (it would add Tungsten Scrap to that List if it did)

**Comment by zhangjunyan2580** [comment]
```java
	List<OreDictMaterialStack> tToBeAdded = new ArrayListNoNulls<>();
	for (int i = 0; i < mContent.size(); i++) {
		OreDictMaterialStack tMaterial = mContent.get(i);
		if (tMaterial == null || tMaterial.mMaterial == MT.NULL || tMaterial.mMaterial == MT.Air || tMaterial.mAmount <= 0) {
			GarbageGT.trash(mContent.remove(i--));
		} else if (tMaterial.mMaterial.mGramPerCubicCentimeter <= WEIGHT_AIR_G_PER_CUBIC_CENTIMETER) {
			GarbageGT.trash(mContent.remove(i--));
			UT.Sounds.send(SFX.MC_FIZZ, this);
		} else if (mTemperature >= tMaterial.mMaterial.mBoilingPoint || (mTemperature > C + 40 && tMaterial.mMaterial.contains(TD.Properties.FLAMMABLE) && !tMaterial.mMaterial.containsAny(TD.Properties.UNBURNABLE, TD.Processing.MELTING))) {
			GarbageGT.trash(mContent.remove(i--));
			UT.Sounds.send(SFX.MC_FIZZ, this);
			if (tMaterial.mMaterial.mBoilingPoint >=  320) try {for (EntityLivingBase tLiving : (List<EntityLivingBase>)worldObj.getEntitiesWithinAABB(EntityLivingBase.class, box(-GAS_RANGE, -1, -GAS_RANGE, GAS_RANGE+1, GAS_RANGE+1, GAS_RANGE+1))) UT.Entities.applyTemperatureDamage(tLiving, tMaterial.mMaterial.mBoilingPoint, 4);} catch(Throwable e) {e.printStackTrace(ERR);}
			if (tMaterial.mMaterial.mBoilingPoint >= 2000) for (int j = 0, k = Math.max(1, UT.Code.bindInt((9 * tMaterial.mAmount) / U)); j < k; j++) WD.fire(worldObj, xCoord-FLAME_RANGE+rng(2*FLAME_RANGE+1), yCoord-1+rng(2+FLAME_RANGE), zCoord-FLAME_RANGE+rng(2*FLAME_RANGE+1), rng(3) != 0);
			if (tMaterial.mMaterial.contains(TD.Properties.EXPLOSIVE)) explode(UT.Code.scale(tMaterial.mAmount, MAX_AMOUNT, 8, F));
			return;
		} else if (!mAcidProof && tMaterial.mMaterial.contains(TD.Properties.ACID)) {
			GarbageGT.trash(mContent.remove(i--));
			UT.Sounds.send(SFX.MC_FIZZ, this);
			setToAir();
			return;
			// Here if a material was boiled the method immediately returns so the materials temporarily removed before will never be added back
		} else if (mTemperature >= tMaterial.mMaterial.mMeltingPoint && (oTemperature <  tMaterial.mMaterial.mMeltingPoint || tNewContent)) {
			// At here if there's new materials it will be temporarily removed and we expect it will be added back below
			mContent.remove(i--);
			OM.stack(tMaterial.mMaterial.mTargetSmelting.mMaterial, UT.Code.units_(tMaterial.mAmount, U, tMaterial.mMaterial.mTargetSmelting.mAmount, F)).addToList(tToBeAdded);
		} else if (mTemperature <  tMaterial.mMaterial.mMeltingPoint && (oTemperature >= tMaterial.mMaterial.mMeltingPoint || tNewContent)) {
			mContent.remove(i--);
			OM.stack(tMaterial.mMaterial.mTargetSolidifying.mMaterial, UT.Code.units_(tMaterial.mAmount, U, tMaterial.mMaterial.mTargetSolidifying.mAmount, F)).addToList(tToBeAdded);
		}
	}
	for (int i = 0; i < tToBeAdded.size(); i++) {
		OreDictMaterialStack tMaterial = tToBeAdded.get(i);
		if (tMaterial == null || tMaterial.mMaterial == MT.NULL || tMaterial.mMaterial == MT.Air || tMaterial.mAmount <= 0) {
			GarbageGT.trash(tToBeAdded.remove(i--));
		} else {
			// Here
			tMaterial.addToList(mContent);
		}
	}

```

**Comment by GregoriusT** [comment]
Wait did that really fix it?

Also if you put the return; back but put it into the if block that causes the crucible to explode, i will be able to 1:1 include your pull request. Just making sure the explosion instantly cancels all further processing, because it might crash otherwise. ;)

if (tMaterial.mMaterial.contains(TD.Properties.EXPLOSIVE)) {
explode(UT.Code.scale(tMaterial.mAmount, MAX_AMOUNT, 8, F));
return;
}

**Comment by zhangjunyan2580** [comment]
Changed that and it should works now.

https://user-images.githubusercontent.com/38811399/231439543-818a398e-b9d8-47c3-8ae6-0b38c32aa07e.mp4


https://user-images.githubusercontent.com/38811399/231439716-b3e7bbfc-ce69-4971-8473-55ae2ef9492a.mp4
