### ISSUE TITLE
Possible Issues about InventoryUnification

### ISSUE THREAD

**Issue by kuzuanpa** [GregTech6/gregtech6#102]
InventoryUnification is sometimes useful, I know. But in Botania, many materials need to interact with tileentitys as EntityItem, and when gregtech "unified" them to gt materials, many recipe can't use at all.
For example: TerraSteel making, Gaia summoning, Pixie trading. all of them only accepts bontania thing but not gt one.
I turned off B:InventoryUnification in general.cfg to false, but It seems only don't unify my inventory, but still unify things I throwed out something or mana pool give something back to me 

Okay I know many of them can be solved by few of MT scripts, but I still want to ask: Is it possible to add a blacklist for InventoryUnification feature, or add a config to turn down entirely?

**Comment by GregoriusT** [comment]
Wait a sec, Botania ingots should be the TARGET of unification, as in unification should turn all GREGTECH ingots into the BOTANIA Variant! I very much know that Unification can cause Issues, but I always try to set my Unification Targets in a way that badly written Mods and non-oredicted Mods become the Target of Unification and not the Source.

See here:


		OreDictManager.INSTANCE.setTarget(OP.gem            , MT.SmokeyQuartz           , MD.BOTA, "quartz", 0);
		OreDictManager.INSTANCE.setTarget(OP.gem            , MT.ManaQuartz             , MD.BOTA, "quartz", 1);
		OreDictManager.INSTANCE.setTarget(OP.gem            , MT.BlazeQuartz            , MD.BOTA, "quartz", 2);
		OreDictManager.INSTANCE.setTarget(OP.gem            , MT.LavenderQuartz         , MD.BOTA, "quartz", 3);
		OreDictManager.INSTANCE.setTarget(OP.gem            , MT.RedQuartz              , MD.BOTA, "quartz", 4);
		OreDictManager.INSTANCE.setTarget(OP.gem            , MT.ElvenQuartz            , MD.BOTA, "quartz", 5);
		OreDictManager.INSTANCE.setTarget(OP.gem            , MT.SunnyQuartz            , MD.BOTA, "quartz", 6);
		OreDictManager.INSTANCE.setTarget(OP.ingot          , MT.Manasteel              , MD.BOTA, "manaResource", 0);
		OreDictManager.INSTANCE.setTarget(OP.gem            , MT.ManaDiamond            , MD.BOTA, "manaResource", 2);
		OreDictManager.INSTANCE.setTarget(OP.stick          , MT.Livingwood             , MD.BOTA, "manaResource", 3);
		OreDictManager.INSTANCE.setTarget(OP.ingot          , MT.Terrasteel             , MD.BOTA, "manaResource", 4);
		OreDictManager.INSTANCE.setTarget(OP.ingot          , MT.ElvenElementium        , MD.BOTA, "manaResource", 7);
		OreDictManager.INSTANCE.setTarget(OP.gem            , MT.ElvenDragonstone       , MD.BOTA, "manaResource", 9);
		OreDictManager.INSTANCE.setTarget(OP.stick          , MT.Dreamwood              , MD.BOTA, "manaResource",13);
		OreDictManager.INSTANCE.setTarget(OP.ingot          , MT.GaiaSpirit             , MD.BOTA, "manaResource",14);
		OreDictManager.INSTANCE.setTarget(OP.nugget         , MT.Manasteel              , MD.BOTA, "manaResource",17);
		OreDictManager.INSTANCE.setTarget(OP.nugget         , MT.Terrasteel             , MD.BOTA, "manaResource",18);
		OreDictManager.INSTANCE.setTarget(OP.nugget         , MT.ElvenElementium        , MD.BOTA, "manaResource",19);
		OreDictManager.INSTANCE.setTarget(OP.blockIngot     , MT.Manasteel              , MD.BOTA, "storage", 0);
		OreDictManager.INSTANCE.setTarget(OP.blockIngot     , MT.Terrasteel             , MD.BOTA, "storage", 1);
		OreDictManager.INSTANCE.setTarget(OP.blockIngot     , MT.ElvenElementium        , MD.BOTA, "storage", 2);
		OreDictManager.INSTANCE.setTarget(OP.blockGem       , MT.ManaDiamond            , MD.BOTA, "storage", 3);
		OreDictManager.INSTANCE.setTarget(OP.blockGem       , MT.ElvenDragonstone       , MD.BOTA, "storage", 4);
		OreDictManager.INSTANCE.setTarget(OP.plate          , MT.Livingwood             , MD.BOTA, "livingwood", 0);
		OreDictManager.INSTANCE.setTarget(OP.plate          , MT.Dreamwood              , MD.BOTA, "dreamwood", 0);
		OreDictManager.INSTANCE.setTarget(OP.plate          , MT.Shimmerwood            , MD.BOTA, "shimmerwoodPlanks", 0);

So what exactly is happening at your end? It should clearly use Botanias Ingots like i specified.

**Comment by kuzuanpa** [comment]
hmm But in my world botania ingots converted to GT one...
And I'm sure I using latest GT version

**Comment by GregoriusT** [comment]
May I see a Screenshot of the Ingots while in your Inventory? Preferably while you Mouse over for a Tooltip?

**Comment by kuzuanpa** [comment]
I dont touched that config...every entry is false.

https://user-images.githubusercontent.com/61902985/213975664-d952c104-b8ed-4011-a1a5-88764a16f069.mp4

**Comment by GregoriusT** [comment]
So I quickly installed "Botania r1.8-249.jar" to test if Unification works on my end, and it does do it properly for me, unlike what your Video is showing. So which Botania Version do you use?

**Comment by kuzuanpa** [comment]
umm I using a modified version by TerraFirmaRescue Team, I don't know if they did something...

**Comment by GregoriusT** [comment]
Uh that Link gives me the GitHub 404 Error...

**Comment by kuzuanpa** [comment]
Oh sorry I write that link by hand and I forget to rename my repo...
And It's there
https://github.com/kuzuanpa/Botania-TFR

**Comment by kuzuanpa** [comment]
hmm I found what commit did I make caused this issue...
https://github.com/kuzuanpa/Botania-TFR/commit/dee2d7d8acf265545ef1cf26ef8bc36a2a140eb3

I just don't want to huge page of warning jump info my face when loading botania.
`
[20:04:45] [Client thread/WARN]: ****************************************
[20:04:45] [Client thread/WARN]: * A broken ore dictionary registration with name manaDiamond has occurred. It adds an item (type: class vazkii.botania.common.item.material.ItemManaResource) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Botania report it to them!
[20:04:45] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(Unknown Source)
[20:04:45] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(Unknown Source)
[20:04:45] [Client thread/WARN]: *  at vazkii.botania.common.item.ModItems.init(ModItems.java:436)
[20:04:45] [Client thread/WARN]: *  at vazkii.botania.common.core.proxy.CommonProxy.preInit(CommonProxy.java:105)
[20:04:45] [Client thread/WARN]: *  at vazkii.botania.client.core.proxy.ClientProxy.preInit(ClientProxy.java:197)
[20:04:45] [Client thread/WARN]: *  at vazkii.botania.common.Botania.preInit(Botania.java:80)...
[20:04:45] [Client thread/WARN]: ****************************************`
like this....

After this commit, botania ingot&gems have their oredict registered correctly, and i think problems may happened there...

**Comment by GregoriusT** [comment]
Ah that Error Message, whatever absolutely broken Version of Botania you are using. DONT. just DONT. It is literally impossible to support it, because of that Error you posted. This is what happens when the fork of a Mod is not updated to what the original Mod already has fixed.

In order to fix the overall Issue there, you need to:
1. Register the Items to the Game Registry
2. Register the Items to the OreDictionary
If you fuck up this basic order of operations, nobody can help...

**Comment by kuzuanpa** [comment]
hmm okay, thanks for your help.
and I even not noticed some oredict register code is in middle of code.I'll try to fix that...
