### ISSUE TITLE
Propane can't fill lighters

### ISSUE THREAD

**Issue by BoBoLittleStar** [GregTech6/gregtech6#104]
Propane can't fill lighters
![image](https://user-images.githubusercontent.com/44244431/218246394-be74d993-e3c0-45ba-a2f5-6d405a1b5f51.png)
Only Butane can do it
![image](https://user-images.githubusercontent.com/44244431/218246410-dde16ddb-b7d1-4bba-90f7-6ef3f42e7391.png)
The only Canning Machine's recipe involving Propane is for Tubes
![image](https://user-images.githubusercontent.com/44244431/218246439-42017a91-0aac-47a4-8050-46c522ddecb3.png)
I didn't see any related items in changelog, so I think this is a bug

**Comment by BoBoLittleStar** [comment]
BTW it worked on 6.15.03, this happened when I upgraded from .03 to .10

**Comment by GregoriusT** [comment]
Dumb Question, the Input Tank Size of the Canning Machine, is it large enough to fill the Lighter in one go or not? Because I suspect I caused the Issue there...

**Comment by BoBoLittleStar** [comment]
It is large enough...
I see, in fact, in your [commitment ](https://github.com/GregTech6/gregtech6/commit/9195e36d96c27168845051db3b33888959c08958)you have removed Propane from lighter recipes.. don't know if it was on purpose or not.
But I remembered in 6.15.03 Propane was able to fill...

**Comment by GregoriusT** [comment]
OH THAT, yeah I got complaints that Propane does not actually work in Lighters in real Life, which was the cause for that. I thought it was the other way around when I saw your Issue, because I confuse those myself too... But yeah cant use Propane for that purpose. Butane is the way to fill them now.

**Comment by BoBoLittleStar** [comment]
Cool 😉
