### ISSUE TITLE
Light weight-o-meter sensor wrong measurments on Raw Ores

### ISSUE THREAD

**Issue by Act0r** [GregTech6/gregtech6#106]
![изображение](https://user-images.githubusercontent.com/3992756/234512472-a88a72bb-8fe4-4864-bbab-5c59a1c8ee00.png)
Tested on Raw Coal Ore and Raw Nether Quartz Ore (not on picture), Raw Salt Are, probably all Raw Ores. Breaks my little early game Crusher automation.

**Comment by GregoriusT** [comment]
Oh right, the fact that they have the "Ore" Type and no byproduct whatsoever, means they technically have zero weight. I will refactor some things to get that to work.

And if you want to just check if there is Items or Stacks inside a Chest or so, there is Item-O-Meters and Stack-O-Meters for that too until then. ;)

**Comment by Act0r** [comment]
Okay, i use that workaround then, thank you

**Comment by GregoriusT** [comment]
Just so you know, that "workaround" is the proper method, lol.

Also the indev build now has it fixed at least. ^^
