### ISSUE TITLE
Drain doesn't work in the case when the block against it is fully filled with fluids

### ISSUE THREAD

**Issue by BoBoLittleStar** [GregTech6/gregtech6#109]
![2023-06-21_08 33 58](https://github.com/GregTech6/gregtech6/assets/44244431/50fad058-32e7-48f3-8fe1-1f6afc2de925)
![2023-06-21_08 34 06](https://github.com/GregTech6/gregtech6/assets/44244431/f23d0929-464d-44bc-8821-e2aaa6e58c6a)
:cry:

**Comment by GregoriusT** [comment]
Drains always try to take the ENTIRE Fluid Block, which can be up to 2000L in size if compressed, if this does not fit into your Pipe in one go, then that exact Issue happens.

Maybe I should change it to at least allow partial drainage of GT Fluids.

**Comment by GregoriusT** [comment]
And fixed indev. ^^
