### ISSUE TITLE
Possible mismatch of texture and behaviour for Filter Blocks

### ISSUE THREAD

**Issue by Tanimodori** [GregTech6/gregtech6#114]
Hi Greg. I've discovered a tricky issue regarding the mismatch of texture and behaviour for Filter Blocks. I'm not sure whether it is intended or a bug so I post it here ^ ^.

## Current Behaviour

Here's the current behaviour of `Filter (Items)` (`gt.multitileentity.30256`) in v6.16.02

Shift+RMB clicking with a *wrench* will mark it as a *main facing* (assumed, for convenience), which has a texture of *item input*.

![image](https://github.com/GregTech6/gregtech6/assets/29478770/cc656de1-4348-4401-afa3-57d1261f4abe)

Shift+RMB clicking with a *monkey wrench* will mark it as a *secondary facing*, which has a texture of *item output*.

![image](https://github.com/GregTech6/gregtech6/assets/29478770/e252a02f-78e5-441d-bf44-6b7596e0ec26)

Inputed items into *main facing* will be outputed into *secondary facing* unconditionally, regardless of the Filter settings (B/W, marked items inside)

![image](https://github.com/GregTech6/gregtech6/assets/29478770/7d8a7baa-a6ad-474f-b927-446f6b791848)

(The config of the Filter above is whitelist, no marked items)

Inputed items into *secondary facing* will be outputed into *main facing* conditionally, as of the Filter settings.

![image](https://github.com/GregTech6/gregtech6/assets/29478770/7aacb97f-7045-4ebc-a81f-0c4effc0706b)

(The config of the Filter above is whitelist, no marked items)

So wrap it up:

| Target                        | Description            |
|-------------------------------|------------------------|
| Primary Facing                | "Item input texture"   |
| Secondary Facing              | "Item output texture"  |
| Primary -> Secondary          | Output unconditionally |
| Others(incl. Sec.) -> Primary | Output conditionally   |

## My assumption

It seems not intuitive to me that "if I input items in the face with input texture, it **won't** get filtered". My assumption is that the texture of two facings are reversed by mistake. It should be intuitive that "if I input items in the face with input texture, it **will** get filtered" 

## Other affected blocks

I've tested `Filter (Ore-Dictionary Prefixes)` which behaves the same as above. I doubt this issue is related to the following blocks.

```
    S:gt.multitileentity.30256=Filter (Items)
    S:gt.multitileentity.30257=Filter (Fluids)
    S:gt.multitileentity.30258=Filter (Items & Fluids)
    S:gt.multitileentity.30259=Filter (Ore-Dictionary Prefixes)
```

The behaviour above is like a Extender but with a filter functionality, maybe the texture of extender is reversed too.

## Environment

* GregTech v6.16.02
* Forge 1614

**Comment by GregoriusT** [comment]
The Filter Blocks are Extenders in nature, the behavior for Extenders is as follows:

Main -> Secondary; because "Main -> Main" does not make sense.
All 5 other Facings -> Main; which also is the one that gets the Filtering.

Filtering Main -> Secondary would not make sense, since it is supposed to redirect whatever the Machine outputs, that you connect this Extender to.

Also the Main Facing does NOT have an Item Input Texture, the Item Input Texture actually has arrows pointing towards the middle Square.

What happened here is that you simply misinterpreted the Secondary Facing, making you THINK it is the reverse of what is actually the point of this Block.

**Comment by Tanimodori** [comment]
Sorry for my mistake. It seems there are a "Others Facing" texture (better names?) outside the "Input" and "Output" texture.

```
Items:
Input  Output  Others
  v       ^      |
>[ ]<   <[ ]>  -[ ]-
  ^       v      |

Fluids:
Input  Output  Others
  v       ^      |
> o <   < o >  - o -
  ^       v      |
```

**Comment by GregoriusT** [comment]
Yeah I know Extenders are complicated to explain, because everyone is used to an Input Output System, and people dont seem to understand that there could be Blocks that make other Blocks bigger.
