### ISSUE TITLE
[Doc] Inconsistency of the effect of IC2 Coolant between code and `gt6fission.pdf`

### ISSUE THREAD

**Issue by Tanimodori** [GregTech6/gregtech6#117]
[gt6fission.pdf](https://gregtech.mechaenetia.com/1.7.10/gt6fission.pdf) ([archived](https://web.archive.org/web/20230922033805/https://gregtech.mechaenetia.com/1.7.10/gt6fission.pdf))

![F(D}PJ4LFE1%Q{HEZ1YA% S](https://github.com/GregTech6/gregtech6/assets/29478770/6f8ae1db-b278-4075-8fa7-23d175af22d5)

https://github.com/GregTech6/gregtech6/blob/75e724c721f57d1c7f76c5e91ce472d51f775489/src/main/java/gregtech/tileentity/energy/reactors/MultiTileEntityReactorRodNuclear.java#L179-L183

IIRC the description `Decreases divisor of factor stat of fuel rods by 1.` should be like `tNeutronDiv -= 1;` in code. Is `gt6fission.pdf` incorrect here?

**Comment by GregoriusT** [comment]
@Erik3003 this would be your thing to know, since you wrote it. ^^

**Comment by Tanimodori** [comment]
I recalled that Erik wrote that pdf based on an in-game book https://github.com/GregTech6/gregtech6/issues/80#issuecomment-1117343247. So those lines may need a revision. ^ ^

https://github.com/GregTech6/gregtech6/blob/75e724c721f57d1c7f76c5e91ce472d51f775489/src/main/java/gregtech/loaders/b/Loader_Books.java#L635-L636

**Comment by Tanimodori** [comment]
Possible typo

https://github.com/GregTech6/gregtech6/blob/75e724c721f57d1c7f76c5e91ce472d51f775489/src/main/java/gregtech/loaders/b/Loader_Books.java#L664

```
For the greatest efficiency you want 
your neutron count one the fuel rod 
                   ^^^ Should be on
stay beneath the maximum stat of that 
fuel rod at all times, while coming 
as close to it as you can.
```

**Comment by Erik3003** [comment]
Yeah, that are typos. The "Deceases divisor of factor stat of fuel rods by 1." is probably a remnant of the older CO2 coolant description.

It should be:
`"Multiplies emission stat of fuel rods by 4. Multiplies factor stat of fuel rods by 2.", `

And the "one" should obviously also be "on".

**Comment by Tanimodori** [comment]
https://github.com/GregTech6/gregtech6/blob/75e724c721f57d1c7f76c5e91ce472d51f775489/src/main/java/gregtech/loaders/b/Loader_Books.java#L678

```
To archive really high neutron counts, 
   ^^^^^^^ achieve?
it is advisable to utilize a critical 
reactor design, though it is also feasible 
to run a burner reactor as a stable design.
```

@Erik3003 May I ask if I've just found another typo? `archive` doesn't make sense here.

**Comment by Tanimodori** [comment]
https://github.com/GregTech6/gregtech6/blob/75e724c721f57d1c7f76c5e91ce472d51f775489/src/main/java/gregtech/loaders/b/Loader_Books.java#L686

```
Emitting 900 neutrons onto the same 
breeder rod with a loss of 500 neutrons 
would mean that 400 neutrons would 
end up on the breeder rod, meaning that 
they would be added to the process of 
turning into an enriched rod each tick.
                                  ^^^^ second
```

There are many "each tick" phrases used. But afaik fission is calculated per second (one tick in a second). I don't think it is accurate to use "each tick" especially the above one. The progress of breeding should be 400 neutrons per second rather than 400n per tick.

**Comment by Erik3003** [comment]
The archive/achieve thing is a typo, the ticks/seconds things is not.
Neutron count on the rods only changes every second, but they get added to the breeding process every tick, just like how energy gets output every tick.

**Comment by Tanimodori** [comment]
So that the update of neutrons count is separated from the update of breeding process and HU output.

**Comment by Tanimodori** [comment]
I've opened a PR that aimed at fixing the in-game description in the book "Fission Reactor Manual" as pointed out above. Extra work is needed to release a new version of the `gt6fission.pdf`.
