### ISSUE TITLE
Suggestion: more replicator recipe 

### ISSUE THREAD

**Issue by klzw2233** [GregTech6/gregtech6#119]
since the Nq ore changed, we need new way to get the most powerful fuel rod. how about add some recipes to get u235 pu239 nq-isotope and other fuel element？ avoid waiting rod to be depleted., let more kinds of fuel rod have chances to be used.

**Comment by GregoriusT** [comment]
You're aware there is a Reactor Breeding Method to get Nq? ;)

**Comment by klzw2233** [comment]
I know the breeder, but it's too slow to get the "rare" fuel isotope,  some isotope is producted by depleted rod.
