### ISSUE TITLE
Crash with cartload during loading

### ISSUE THREAD

**Issue by czhang7175** [GregTech6/gregtech6#121]
https://www.curseforge.com/minecraft/mc-mods/cartload

**Comment by GregoriusT** [comment]
Why not put the Crash Log?

**Comment by czhang7175** [comment]
> Why not put the Crash Log?
[crash-2024-01-13_00.29.30-client.txt](https://github.com/GregTech6/gregtech6/files/13926902/crash-2024-01-13_00.29.30-client.txt)

**Comment by GregoriusT** [comment]
You accused the wrong mod there, it's likely gtplusplus doing it, as it is a GT5 Addon not a GT6 Addon as far as i know.

**Comment by czhang7175** [comment]
I saw it, I misplaced it…..
