### ISSUE TITLE
Gunpowder crafting recipes are missing

### ISSUE THREAD

**Issue by Razenpok** [GregTech6/gregtech6#122]
When I click on the gunpowder in NEI, no recipes show up.

This bug occurred first in 6.16.02, while 6.16.01 had it working fine.

I have no idea why, but maybe this?
https://github.com/GregTech6/gregtech6/commit/31dc8528bd1a8f6d5eaa4d0746bc4932a858b5bf

Looks suspicious with this `MT.Gunpowder.setLocal("Boompowder");` => `MT.Gunpowder.setLocal("Crossbow Powder");` change

**Comment by GregoriusT** [comment]
This is actually impossible, as there is a ton of Recipe Lists that all show Recipes for me, please describe the actual Issue. Is NEI just not showing Recipes to you at all in the first place?

**Comment by Razenpok** [comment]
Okay, I've found the problem. I'm playing a stripped-down version of the Bears GP6 pack, which I made several years ago, and I was updating GT itself whenever I wanted to play again. It has `NotEnoughItems-1.7.10-2.0.1-GTNH-universal`, which causes this bug. I just checked, and neither NEI provided by [GT Downloads page](https://gregtech.overminddl1.com/downloads/gregtech_1.7.10/index.html) nor newer GTNH NEI versions have this bug.

Would you recommend sticking to the version provided by GT Downloads, or is it okay to use the newer GTNH version? I know that Bear still plays with the GTNH one, but I'm not sure if it has any compatibility issues with GT.

Repro steps:
1. Create a new Survival world
2. Open inventory
3. Find Gunpowder using NEI
4. Click on Gunpowder


https://github.com/GregTech6/gregtech6/assets/8434406/ae904168-ecd1-49eb-b00d-c8d4dd4e9de5

**Comment by GregoriusT** [comment]
You can use either and it should be fine.
