### ISSUE TITLE
unexpected Energy loss when the soild burning box use more than 1 fuels at once.

### ISSUE THREAD

**Issue by mordds** [GregTech6/gregtech6#127]
when the soild burning box use more than 1 fuels at once,the soild generator will only generate 1 fuel's HU.
for example,for 1/72 coal dust,the burning box will use 4 1/72 coal dust at once.but it only generate 550 HU,which is equal to 1 1/72 coal dust should generates.
after view the source code,I think the problem occurs at  gregapi.recipes.maps.RecipeMapFurnaceFuel

``` 
for (int i = 1; i < 64; i++) {
	ItemStack tAshes = OM.dust(tMaterial.mMaterial, tMaterial.mAmount * i);
	if (ST.valid(tAshes)) {
		rRecipe = new Recipe(F, F, T, ST.array(ST.amount(i, aInputs[0])), ST.array(tAshes), null, null, null, null, tFuelValue * EU_PER_FURNACE_TICK, -1, 0);
		break;
	}
}
```

in this block of code,the program try to find a proper amount of fuel to consume in order to generate a existed size of ash ,but the energy do not multiplied the amount of fuel.and this is the most possible cause of the problem mentioned in title.

**Comment by GregoriusT** [comment]
Oh shit you actually found a bug!
