### ISSUE TITLE
Item Barrel & Plastic Storage Box BUG

### ISSUE THREAD

**Issue by BoBoLittleStar** [GregTech6/gregtech6#13]
Replication: put a dust of unit 1 into the barrel, then put **_x_** small dusts (any of 1/4, 1/9, 1/72 ones). Every time when player uses a soft hammer to reset the barrel and re-put dusts of any material, it pops out **_x_** small dusts of the same material as the one stored in.
Minecraft version: 1.7.10
Minecraft Forge: 10.13.4.1558
GregTech version: 6.12.01 (but nothing relevant in later change logs were seen)

**Comment by GregoriusT** [comment]
There we go, it's fixed in the upcoming Version. Was the obvious "did not set the Partial Units to 0 after dropping the Items" Bug
