### ISSUE TITLE
Cobalt-60 has 43 neutrons?

### ISSUE THREAD

**Issue by BoBoLittleStar** [GregTech6/gregtech6#23]
![161596279059_ pic](https://user-images.githubusercontent.com/44244431/89100217-4a91cb00-d3ed-11ea-9675-021ecbea74df.jpg)

**Comment by GregoriusT** [comment]
Good catch, also it seems like GitHub should at least say that the Issue got closed because I used "Fixes #23" in that commit. Oh well, it is fixed now. XD
