### ISSUE TITLE
Add more OresBedrock flowers

### ISSUE THREAD

**Issue by jihuayu** [GregTech6/gregtech6#25]
Many OresBedrock flowers are Orechid.
It make me could not find the some OresBedrock.
Can I add some flower?
Thanks.

**Comment by GregoriusT** [comment]
Uhm why are most of those Flowers Copypaste of other Stuff or recolorized duplicates? You don't have to fill the entire MetaData Limit of my Flowers with what one could easily describe as "Filler".

Each of my Plants has the purpose of pointing towards one Type of Ore (except the Orechid, which is for anything I do not have a Flower for). Meanwhile your Flowers are not looking very well thought through, they are just there to fill a gap the most lazy way possible.

Why exactly does Stolzite have a Flower that is different from all the other Tungsten Ores? Is there anything special about it?

And why are there Vine Textures amoung the Flowers? None of them are going to be actual Vines, they are just regular Flowers.

At the very least I am planning to give Hexorium its own Flower soon, but that is not really related to your Issue. I still need to think of other Flower Types and Names for the Stuff that really needs some actual Indicator Flower.

Until then, just pick up some of the Rocks around the Orechids so you can see what Ore is actually down below.

**Comment by jihuayu** [comment]
Oh, I am sorry.
Thanks.

**Comment by GregoriusT** [comment]
You dont need to feel sorry, this was just criticism on how you did it. There definitely needs to be more Flowers, you are right with that. ^^
