### ISSUE TITLE
dilithium ore

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [GregTech6/gregtech6#28]
NEI seems to indicate that GT6 doesn't generate it's own dilithium ore or dilithium bedrock ore. Could dilithium bedrock ore generate by default on Mars? (for advanced Rocketry warp drive)

**Comment by GregoriusT** [comment]
What does GT6 need that Stuff for? So far there is not really any uses for it, is there?

**Comment by bHXDgiuMa5yLHyC8** [comment]
You're right that there's no GT6 uses for it, I just wanted it for Advanced Rocketry. Is there a way I can set dilithium bedrock ore to generate (on Mars) using the configs?

**Comment by GregoriusT** [comment]
I decided to add it to Mars and Planets, so I guess you dont need to. Explaining how to add Bedrock Veins through the Config is uhhhhh way too complicated for me to be explaining,
