### ISSUE TITLE
Swords aren't craftable except from steel

### ISSUE THREAD

**Issue by Razenpok** [GregTech6/gregtech6#31]
So I'm playing "GT6 Only 4.0 FINAL" pack by Bear which uses GT 6.12.00 and it appears that there aren't any recipes for swords except for flint and steel ones. Given that 6.14.02 removed flint swords, I guess now the only sword is the steel one?

**Comment by GregoriusT** [comment]
I removed Stone Swords quite a while ago. Use Stone Clubs for fighting instead. ;)

also I would recommend updating GT6 from time to time. ^^

If you need to cut Stuff, the Flint Knife still exists, same for Obsidian.

**Comment by Razenpok** [comment]
Thanks!
