### ISSUE TITLE
[Suggestion] NEI recipe numbers with separator and item tooltips

### ISSUE THREAD

**Issue by Miradae** [GregTech6/gregtech6#32]
Currently reading many of the GT6u recipes can be cumbersome since there is no 1000s separator. Same for tooltips on things like tanks, drums, batteries etc

**Comment by Miradae** [comment]
has been added

**Comment by GregoriusT** [comment]
Uhh this is regular GT6 not GT6U, lol. Also it already exists? What was the purpose of this Issue? XD

**Comment by Miradae** [comment]
I wrote the issue on GT6u then thought it would make sense to write it here, so i copied the issue. Then found out it got already fixed but somehow never saw it in the changelog, so i closed it again xD
