### ISSUE TITLE
[Compat] Forestry Backpacks & Magnetic Tools

### ISSUE THREAD

**Issue by Miradae** [GregTech6/gregtech6#35]
Currently forestry backpacks are not compatible with magnetic tools like the drill. Items mined with it will go into the inventory instead of the backpack and if the inventory is full just drop on the ground.
It would be cool if there was some compat that makes magnetic tools try to insert into backpacks first (or at least when inventory is full, instead of just dropping on the ground)

**Comment by GregoriusT** [comment]
Okay Bear tested it, it works now. ^^
