### ISSUE TITLE
Red alloy wires behave unpredictably after world restart

### ISSUE THREAD

**Issue by Alfaksan** [GregTech6/gregtech6#39]
Mods: Bear's Survivng Take 2 1.4 + OptiFine + InventoryTweaks + RealBench

Description: After world restart some red alloy wires don't activate molds (see attached video https://youtu.be/6OnYKfwRVwg )

Steps to reproduce (at least for me):
1. Open attached world, fill burning box, light it up.
2. Wait till thermometer activates molds
3. If everything works correctly, exit world and open it again to try to catch this behaviour

[Red test.zip](https://github.com/GregTech6/gregtech6/files/6144659/Red.test.zip)
Attached world where video was recorded

@GregoriusT on your site you said to mention you in issues ^^

**Comment by GregoriusT** [comment]
Hahaha, you dont need to mention me on my own Projects, that was more meant for other Mods GitHub Pages if the Issue remotely involves me. ;)

It is hard to see in the Video, are the Wires glowing in the dark when active? This Issue might be the Molds themselves not reacting to the Wires at all for some reason. Just asking to make sure I look at the right location. ^^

**Comment by Alfaksan** [comment]
Pre-restart it looks like this
![image](https://user-images.githubusercontent.com/39828534/111226240-e0cbd780-85f1-11eb-9030-9a555c5bade2.png)
After restart like this
![image](https://user-images.githubusercontent.com/39828534/111226315-fc36e280-85f1-11eb-9102-ff6eaa49d223.png)
All are lit up, but 1 mold was not activated

**Comment by GregoriusT** [comment]
Okay so the Issue is definitely the Mold itself not reacting appropriately.

While I look into the issue, can you attach a Repeater as a Cover to the Wire, pointing into the Molds?

**Comment by Alfaksan** [comment]
Didn't help, unfortunately. Now 2 other molds stopped working
![image](https://user-images.githubusercontent.com/39828534/111228667-a106ef00-85f5-11eb-8484-a4894c97eb37.png)

Can upload a video if needed

**Comment by GregoriusT** [comment]
Can you try using vanilla Redstone? I would like to make sure that this is even a Redstone Issue, and not the Crucible Crossings somehow screwing up.

**Comment by Alfaksan** [comment]
Regular redstone don't work at all
![image](https://user-images.githubusercontent.com/39828534/111231210-eb8a6a80-85f9-11eb-8307-001c90d07231.png)
 Not before, not after restart

**Comment by GregoriusT** [comment]
That isn't how vanilla redstone works, elevate the whole line of redstone dust one block up, as if you wanted to power 4 Pistons!

**Comment by Alfaksan** [comment]
Erm.. Like this? 
![image](https://user-images.githubusercontent.com/39828534/111232724-c4816800-85fc-11eb-92a8-1eb2e1efd2a9.png)

**Comment by GregoriusT** [comment]
Weird, this should have worked. And with regular Repeaters pointing directly into the Molds?

**Comment by Alfaksan** [comment]
Also nope. Not with non-elevated repeaters:
![image](https://user-images.githubusercontent.com/39828534/111272538-d2a6a700-8643-11eb-9590-3da451ffdda8.png)
And also not with elevated repeaters:
![image](https://user-images.githubusercontent.com/39828534/111272645-f10ca280-8643-11eb-9c8e-5254167078f8.png)

**Comment by Miradae** [comment]
I did some further testing with the setup:
Replaced all red alloy wires with signalum wires: no change in behaviour, bug still happens
Giving constant redstone signal to "bugged" molds: Molds work now as expected
![2021-03-16_09 51 30](https://user-images.githubusercontent.com/45173115/111282562-6bd2bf00-863e-11eb-8549-a5d19dc04182.png)
Using vanilla redstone repeater to give signals to molds: Molds dont work at all, even without reload of the world (i tried all different 'delay' settings on the repeater
![2021-03-16_09 58 40](https://user-images.githubusercontent.com/45173115/111282705-902e9b80-863e-11eb-8b58-6b442a624e2d.png)
Using the same setup as in the redstone repeater setup but giving a constant active signal on the wire makes all molds work (did this to test if the repeater setup should work in theory)
I did all these tests in a pure GT6 + NEI world, so other mods, newest released version of GT6.
I hope that helps a little bit to find the culprit.

**Comment by GregoriusT** [comment]
Wow, yep the Molds must be broken somehow. I just dont know why... yet. But this is all options I could ask for so the rest is up to me to find out. ^^

**Comment by GregoriusT** [comment]
If you update the redstone after reloading the World, the Molds WILL work right?

**Comment by GregoriusT** [comment]
So I would like to know one more thing, are you restarting the entire Minecraft Client between tests or are you exiting and entering the World?

**Comment by Alfaksan** [comment]
When testing and reporting I was just exiting and entering the world. But I have mold issue in my main playing world as well and it is reproducible with full client restart.

**Comment by GregoriusT** [comment]
I will ask this one again:
If you update the redstone after reloading the World, the Molds WILL work right?

**Comment by Miradae** [comment]
From my tests, breaking and replacing a redstone cable in between or break+replace of the cable touching the mold, does NOT help fix the issue.
Sending a long redstone signal through the entire cable line (e.g. flipping a lever on, then off again), WILL lead to the molds working again

**Comment by Alfaksan** [comment]
Replacing cables connecting to non-working molds does fix them for me. I currently use it like a workaround and replace most wires after world restart

**Comment by GregoriusT** [comment]
Can you two try this Version? https://gregtech.mechaenetia.com/secretdownloads/

I rewrote a bit of the Mold Code. I did not test it yet because I went to bed after writing it, but it should work.

**Comment by Alfaksan** [comment]
Non-reproducible with this version for me

**Comment by GregoriusT** [comment]
Does that mean it now finally works perfectly, or that I fucked it up so much that the molds dont even work? XD

**Comment by Alfaksan** [comment]
Yeah sorry I was not clear - everything works perfectly, thanks. I wonder can I use this snapshot or is it unstable and has other changes?

**Comment by GregoriusT** [comment]
While it has other Stuff, the most unstable thing about it is the Molds, so you should be fine. XD

**Comment by Miradae** [comment]
works for me too, thx greg :)
