### ISSUE TITLE
Sometimes get potion effects, plus taking damage when going in a save

### ISSUE THREAD

**Issue by BoBoLittleStar** [GregTech6/gregtech6#44]
<img width="245" alt="Screen Shot 2021-07-23 at 19 22 30" src="https://user-images.githubusercontent.com/44244431/126775235-cc49da1e-12d3-4d8f-a82f-0e7f4f6b2eb3.png">
...and usually I die from this. The effects are much like when I ate or drank too much same stuff in a row, which I'm sure I didn't. Also, there are no effects each time I quit the game.
Btw the version is 6.14.15

**Comment by BoBoLittleStar** [comment]
Ok another bug... When I rolled back to the last save and went in once again, the effects were present, but were gone when I went into another dimension (at least that was what happened when I went to overworld from the End)

**Comment by GregoriusT** [comment]
Did you walk into one of those very visible white gas pockets? (not visible while you're inside of them) That might be the Issue you are having.

**Comment by BoBoLittleStar** [comment]
Surely not, unless there is some in the End

**Comment by BoBoLittleStar** [comment]
You've probably mis-red the title.. It's when I'm starting a game not going into a "cave"

**Comment by GregoriusT** [comment]
Do you hold anything Radioactive inside your Inventory? That might be the Issue.

**Comment by BoBoLittleStar** [comment]
No. If there were anything radioactive then I would've been poisoned and I would've noticed that. Also every time when I quit the game I'm sure there aren't any effects, because I just don't like it

**Comment by GregoriusT** [comment]
The thing that is looking weird to me is Nausea II, because nothing in GT6 gives you that Effect without also giving you other Effects. This whole combination of Effects is not something GT6 could actually cause. Are you sure you dont have another Mod like Enviromine or so installed that does such things?

**Comment by BoBoLittleStar** [comment]
Actually this is just for showing that I'm having weird effects at this time. Some of them counted to zero when I took the screenshot so they just disappeared.
This is my mod pack: I've highlighted the major ones
<img width="906" alt="image" src="https://user-images.githubusercontent.com/44244431/126803389-2d5845c7-29e0-431a-b32f-5bb79f34ec7d.png">

**Comment by BoBoLittleStar** [comment]
https://user-images.githubusercontent.com/44244431/126805037-5b222749-88a3-44b2-a14e-7641b1a2ecde.mp4

**Comment by GregoriusT** [comment]
And these Effects never vanish or so? They are supposed to vanish after Death for sure, I would be worried if they persisted through Death, because they definitely are not supposed to.

**Comment by BoBoLittleStar** [comment]
After death they are vanished. But it's too annoying, especially when I'm far away from home or of high level

**Comment by GregoriusT** [comment]
I think I found the Issue, maybe, seems like when you have zero effects on you it doesn't save any data, which usually is intended, but if old data exists it loads that old data instead because it forgets deleting the old Data. This probably happened while you logged in or out while you were about to die from Food Effects, or you just used a Portal instead of logging.

Anyways I think I got it fixed.

**Comment by GregoriusT** [comment]
https://gregtech.mechaenetia.com/secretdownloads/

Here is a Version that should fix your Issue. It should be stable for the next few hours. ^^

**Comment by BoBoLittleStar** [comment]
let me try!

**Comment by GregoriusT** [comment]
You MIGHT end up getting the Effects ONCE, but after that it should never repeat itself anymore.
