### ISSUE TITLE
You sure about this? xDDD

### ISSUE THREAD

**Issue by BoBoLittleStar** [GregTech6/gregtech6#47]
Barbeque sauce OP lol

![image](https://user-images.githubusercontent.com/44244431/131209794-706c9fa3-7f9a-433c-8c92-7b0e12b8349e.png)

**Comment by GregoriusT** [comment]
What the F?! Did I not make sure Tofu cant be used on that one... I did for all the other meat Stuffs. XD

**Comment by BoBoLittleStar** [comment]
Also green emerald : P

**Comment by GregoriusT** [comment]
The Code literally says that Tofu is blacklisted from that Recipe, just WHAT THE?!

**Comment by BoBoLittleStar** [comment]
Btw It's not a displaying issue. I actually just made one base on this recipe.

**Comment by GregoriusT** [comment]
Uh I just opened MC and that Recipe does not exist for me. Which Version are you running on?

**Comment by BoBoLittleStar** [comment]
Oh yeah.

It's 6.14.19. I didn't read through the latest changelog. Maybe you've fixed it by accident 😆

**Comment by GregoriusT** [comment]
Oh yeah I might have fixed this while making Sandwiches, guess this case is closed then- XD
