### ISSUE TITLE
Why is the efficiency of niobium titanium carbide turbine not 66.66%

### ISSUE THREAD

**Issue by TheOnlySakura** [GregTech6/gregtech6#48]
Why is the efficiency of niobium titanium carbide turbine not 66.66%

**Comment by GregoriusT** [comment]
Uh I dont sit at a computer with IDE right now but what exactly is wrong?

**Comment by yuesha-yc** [comment]
You should report this to https://github.com/GregTech6-Unofficial/GregTech6-Unofficial
