### ISSUE TITLE
TFC(+) compat: Scaling up GT6 (tool) damage values so to fit TFC(+)'s standards (when TFC(+) is detected)

### ISSUE THREAD

**Issue by Unemployed1994** [GregTech6/gregtech6#5]
For instance, a wrought iron sword in TFC(+) does 500 DMG while one in GT6 does 6 DMG, meaning that the TFC(+) one does 83.3333... times the damage. It would be cool if GT6, when detecting TerraFirmaCraft(Plus), were to scale up all damage values by a factor of, e.g. 83.33333... so to fit its standards.

**Comment by GregoriusT** [comment]
Weird, I thought I fixed that already, but I am very very sure the tooltips would be broken in that case because I dont remember doing the tooltips for the increased damage

**Comment by 4hubert** [comment]
It could be that it only doesn't seem to work with TFC+. I tried it out myself and GT6 swords don't do much more damage than your fists do on TFC+ mobs.

**Comment by GregoriusT** [comment]
Okay I fixed it. TFC+ will be detected like TFC in the future.
