### ISSUE TITLE
[Website] Thaumcraft is said to "Require" Thaumic Fixer, GT6 has replaced it and crashes if Thaumic Fixer is present

### ISSUE THREAD

**Issue by thePalindrome** [GregTech6/gregtech6#52]
A rather simple bit of outdated information. Thaumic Fixer is a mod that fixes thaumometer lag with large amounts of aspects, but apparently GT6 does it better (and does it itself), and as a result crashes if thaumic fixer is present to avoid issues:

```
java.lang.RuntimeException: java.lang.RuntimeException: Please uninstall ThaumicFixer, GregTech-6 itself by now fixes the Thaumometer Lag Issue in a far better and less 'Thaumcraft-Addons breaking' way than Thaumic Fixer.
```
The solution here is mainly just to remove the note from the website, dropping the dependencies down to just Baubles

**Comment by GregoriusT** [comment]
Wait, where on the Website does it still say ThaumicFixer is required? I thought I got rid of all mentions...

**Comment by thePalindrome** [comment]
https://gregtech.overminddl1.com/1.7.10/compatibility/ , yeah. Looks like you just fixed it, so I guess that's this closed out!
Thanks for the help ^v^
