### ISSUE TITLE
Ender Garbage Dump is spitting items from other worlds

### ISSUE THREAD

**Issue by BoBoLittleStar** [GregTech6/gregtech6#55]
: |

**Comment by GregoriusT** [comment]
Define other Worlds. If it is other Dimensions, that is normal, if it is other Savegames, that would be a Bug.

**Comment by BoBoLittleStar** [comment]
It's from other save.

**Comment by GregoriusT** [comment]
Just making sure, but your GT6 is up to date, RIGHT?

**Comment by GregoriusT** [comment]
Also double making sure: Are you sure those Items are from another World and not from the World you are playing in? Despawned Items happen pretty much everywhere, so that is something to check for too.

**Comment by BoBoLittleStar** [comment]
Version 6.14.21
And we are pretty sure about the bug cuz player's head is not likely to be something we normally get
![捕获](https://user-images.githubusercontent.com/44244431/140654032-64d1c4a6-a9ed-4c86-8295-38f8701520a3.PNG)

**Comment by GregoriusT** [comment]
So I think this should work in the upcoming Version now. Kinda hard for me personally to reproduce but I think I added enough safeguards now. ^^
