### ISSUE TITLE
Chromium Burning Box's output power doesn't match Chromium Steam Boiler's input power

### ISSUE THREAD

**Issue by BoBoLittleStar** [GregTech6/gregtech6#56]
![image](https://user-images.githubusercontent.com/44244431/140650406-e47c6e73-649b-4118-9fd0-5337c8bf82c7.png)
![6087de0ec9bf929b4d6b344186bf4ef](https://user-images.githubusercontent.com/44244431/140650409-44c17966-8da7-4d27-91da-f825ac04cccb.png)

Chromium Burning Box matches Titanium Steam Boiler and vice versa, don't know if it's a mistake or not

**Comment by GregoriusT** [comment]
This is correct, even if it does not look like it. Not like I could change it anyways without screwing over everyone who has those Machines in their Base.

**Comment by BoBoLittleStar** [comment]
Indeed : (
