### ISSUE TITLE
Wondering why this is happening

### ISSUE THREAD

**Issue by BoBoLittleStar** [GregTech6/gregtech6#61]
https://user-images.githubusercontent.com/44244431/145214989-f9c74c8f-a658-4a7f-abcd-09678d663ca9.mp4

**Comment by GregoriusT** [comment]
I think Railcraft has a 16000L Limit on its Tanks when filling Items. Lemme check...

Okay what the actual fuck, Railcrafts Code says 4000, this is 16000...

Waaaaait, why does Railcraft not drain Fluid from its Tank?! Did you update Railcraft recently? I know there was a one time update.

**Comment by BoBoLittleStar** [comment]
The thing is they are different fluids. The oil in the Drum is Oil from BuildCraft, but the Railcraft tank stores Light Oil. I've tried vanilla Water Bucket and it's all good, but Water in a Drum just disappears when I put it in. I'm not sure which mod the problem belongs to.

**Comment by GregoriusT** [comment]
Wait WHAT?! So the Railcraft Tank just converts Oil, gives you wrong amounts, and does not drain anything from its internal Tank, ALL AT ONCE?!

**Comment by BoBoLittleStar** [comment]
Actually there's no issue if the liquids match. But if they don't, the liquid in the Drum just disappears. I also tried putting Water Drum into Sluice Tank, the Water just disappears

**Comment by GregoriusT** [comment]
Sluice Tank? As in GT6 Sluice? okay I need a screenshot/shortvideo of that happening please.

**Comment by BoBoLittleStar** [comment]
https://user-images.githubusercontent.com/44244431/145614043-387aad33-4bac-4109-a1ab-623b23ee17ed.mp4

**Comment by GregoriusT** [comment]
This must be a pure Railcraft Bug, and you cant update Railcraft to see if it gets fixed that way? As I said, I know there was a random Railcraft Update a bit ago to fix some Issues.

Anyways, not like I could do anything against it on my end, so I have to close this Issue here, and maybe recommend to not use Railcraft Tanks.
