### ISSUE TITLE
Magnetic Separator not processing until block updates

### ISSUE THREAD

**Issue by BoBoLittleStar** [GregTech6/gregtech6#62]
We're still playing 6.14.21 fyi

https://user-images.githubusercontent.com/44244431/145684430-be5a183c-a528-49a3-872d-6d8c52f5992a.mp4

**Comment by GregoriusT** [comment]
How did you get it into that unblockupdated state in the first place?

**Comment by BoBoLittleStar** [comment]
One of the cases is once the Polarizer finished its work, the Magnetic Separator stops.

**Comment by GregoriusT** [comment]
OOOOH yeah only ONE of the Machiens is allowed to have the Auto Cover on it. You need to figure out a different way with different Covers if you want it to work with an "OR" instead of an "If Polarizer tells it what to do"- ;)
