### ISSUE TITLE
Item filter is not working on item pipes

### ISSUE THREAD

**Issue by BoBoLittleStar** [GregTech6/gregtech6#63]
As you can see the pipes are not connected properly when an item filter is in-between. I don't know if it's a bug or made deliberately.

https://user-images.githubusercontent.com/44244431/146955206-08785ae4-54cf-4165-bb63-e32062c47d92.mp4

**Comment by GregoriusT** [comment]
Item Pipes do not check whatever is inbetween them, so Item Filters would not work, meaning I had to make sure those Filters DO NOT let the Pipes connect in any way, in fact Item Filters even forcefully disconnect Pipes they are attached to if they see there is a Pipe on both ends.
