### ISSUE TITLE
GTWW compatibility bug (two IDs for galvanized steel wall block)

### ISSUE THREAD

**Issue by Klayto-235** [GregTech6/gregtech6#66]
GTWW adds galvanized steel tanks and drums, but it seems to add its own version of the walls to do so. Same name, tooltip and recipe; different ID and mod. Tried to set up a fusion reactor and found out the reason it didn't work was due to the walls being from GTWW instead of GT. Made GT walls in laser welder as GTWW walls don't have a recipe for that.

**Comment by GregoriusT** [comment]
Yeah that is something that GTWW has to fix, I cant really do anything about it.
