### ISSUE TITLE
I want an authorization

### ISSUE THREAD

**Issue by ProjectYinai** [GregTech6/gregtech6#67]
HI, Mr.Greg, Im your fan, Im glad you made GT6 and Im still playing and having a lot of fun. Now Im making a little game (not about MC) and want to use some material package of GT6. Is that OK? Of course, this game is free and non-commercial.

**Comment by ProjectYinai** [comment]
Actually, I just want to use icons like mixer, bathing and so on. I like these icons full of technology. I'm probably not going to touch anything else at all. After all, I don't have that strength to use anything else but icons XD.

**Comment by ProjectYinai** [comment]
It seems to have caused some misunderstanding, sorry.

**Comment by GregoriusT** [comment]
Every Asset I made, except for the few ones containing my Logos are licensed CC0. ;)

https://github.com/GregTech6/gregtech6/blob/master/LICENSE.assets
https://github.com/GregTech6/gregtech6/blob/master/COPYING.assets

**Comment by ProjectYinai** [comment]
wow, thank you! could I kiss you? XD.
The great GT will unify MC in the end, wowowowowowowowow~~~
