### ISSUE TITLE
Drums sometimes can contain Steam?

### ISSUE THREAD

**Issue by BoBoLittleStar** [GregTech6/gregtech6#69]
I don't know what else condition it might need but Ender Garbage Dump can fill Steam into the Drum below it, contradicting the tips of Steam, "Cannot be stored in any normal GT6 Storage Tanks"
Not a big issue though : )
![2022-02-05_14 50 12](https://user-images.githubusercontent.com/44244431/152632086-cdb5a04b-22a0-4930-843b-05ac4673e610.png)

**Comment by GregoriusT** [comment]
What type of Steam is that? Might not be GT6/Railcraft Steam, is that IC2 Steam?

**Comment by BoBoLittleStar** [comment]
It does make noise. That's why I think it's GT Steam. It looks like it does dump the Steam into the garbage again, since the Steam in the Ender Garbage Dump doesn't drop.

This happens once I placed one Drum first on the ground, then placed the Ender Garbage Dump. I tried some other ways to reproduce it but it didn't work.

**Comment by GregoriusT** [comment]
Yeah the Drum doesn't actually "contain" the Steam, it just vents it out, with the Steam itself going to the Garbage, which then gets inserted into the Drum again. That is just a weird Setup and not a Bug. ;)
