### ISSUE TITLE
Berry Bushes sometimes disappear

### ISSUE THREAD

**Issue by BoBoLittleStar** [GregTech6/gregtech6#73]
Definitely no one broke the bushes, but days after they were placed some just disappeared.
![2022-03-11_00 12 37](https://user-images.githubusercontent.com/44244431/157706550-0e780042-8e67-4523-88f0-6833830b31fb.png)

**Comment by GregoriusT** [comment]
Is that at a Chunk Border? Those missing Bushes might have been across a Chunk Border.

**Comment by BoBoLittleStar** [comment]
Yes it is, but even the top bush drops
![2022-03-11_21 11 05](https://user-images.githubusercontent.com/44244431/157872906-743487e5-3f6d-4909-b5be-e93bb3710bb9.png)

**Comment by GregoriusT** [comment]
This issue should be fixed in the Test Version now. ^^
