### ISSUE TITLE
[Suggestion] Add config option to make GT water flow like vanilla water

### ISSUE THREAD

**Issue by kappa-maintainer** [GregTech6/gregtech6#74]
I am using GregGen to generate my world, but the cave connectivity it brought allow GT water to fill every cave under swamp and ocean. Mining under dirty water with debuff is not fun at all, maybe add a config option to tweak water's mechanism is a good idea.

**Comment by GregoriusT** [comment]
Wait wasn't there an option to limit spread of the different types of Water?

    B:OceanBlocksSpreadToAir=false

This would be one example, and I dont think Rivers and Swamps spread infinitely. I really need to get my Dev Environment up and running on my new Computer...

**Comment by kappa-maintainer** [comment]
I have toggled that option, but it did not seem to be what I want. The main problem is, GT water can spread horizontally in the air without hitting blocks, so even one source block can easily fill a whole giant cave system.

**Comment by kappa-maintainer** [comment]
Some video and screenshots:
https://webmshare.com/jx45g
![2022-03-16_12 50 39](https://user-images.githubusercontent.com/11038263/158519448-c2f1789e-eafb-4944-b62e-84b53b78fe09.png)
![2022-03-16_12 46 06](https://user-images.githubusercontent.com/11038263/158519461-c702da23-ddd5-4880-8145-0f6c273add6e.png)
![2022-03-16_12 45 13](https://user-images.githubusercontent.com/11038263/158519472-5fa04274-54df-47f5-a438-89a42fcefec3.png)
![2022-03-16_12 40 42](https://user-images.githubusercontent.com/11038263/158519489-3376b4b5-734f-4aaa-a2ec-d71c3cf5899d.png)

**Comment by kappa-maintainer** [comment]
You may want to look at my commit to fix this:
https://github.com/kappa-maintainer/gregtech6/commit/8b3a3bad0644c78a74edd7a3f9baed75c8e9acef
Basically, it reintroduced the vanilla horizontal flowing check, and reduced seawater's source making ability.

**Comment by GregoriusT** [comment]
Are you sure you know what you are doing there? Pretty sure only one of those checks would need changing to fix the whole sideways flowing thing, not literally all of them. At that point you could just disable Worldgen of Riverwater itself (yes config exists for that too) and get the same experience, since Drains and Stuff still do Biome based checks for backwards compatibility with older Rivers.

But yeah I will add a Config for that one, once I am back at developing Stuff instead of playing Factorio...

**Comment by kappa-maintainer** [comment]
Well, I already have a survival world and I don't want to regenerate it or deal with WorldEdit yet, so I decide to do some coding. These new fluids have their usages, that's why I tend to preserve them. At last, those extra checks are used to stop seawater from creating more source blocks in many circumstances. I didn't touch the swamp water part, just too lazy to check another class.

**Comment by kappa-maintainer** [comment]
When I jump on grass path blocks from Et Futurum, there is a small chance of glitching player movement. It seems caused by GT grass blocks' incorrect bounding box, so I made another commit:
https://github.com/kappa-maintainer/gregtech6/commit/67b5ac122f5d80cdb1d99e97a40229b00caf96d3

**Comment by GregoriusT** [comment]
The GT6 Grass Path Blocks have the correct intended bounding Box. Also how exactly do you get the Et Futurum Grass Path Blocks in the first place? GT6 Shovels dont make those.

**Comment by kappa-maintainer** [comment]
I installed [Village Names](https://www.curseforge.com/minecraft/mc-mods/village-names/) to get some new village building, but it can only use grass path from Et Futurum. When I jumped on those blocks, things happened...

**Comment by kappa-maintainer** [comment]
GT6's current grass path is 16 * 16 * 16 in game, not the correct 16 * 15 * 16

**Comment by GregoriusT** [comment]
That is because there is worse issues if I make it Soulsand height, resulting in Slabs and Stairs and such not being usable adjacent to paths at all. This again is very much intended to be using a full Block Collision Box.

**Comment by kappa-maintainer** [comment]
So that's why EF's path block has a full block option...
But that's because step height is 0.5F in 1.7.10, not higher version's 0.6F.
Maybe changing this value at the EntityJoinWorldEvent is a possible workaround?
https://github.com/kappa-maintainer/gregtech6/commit/2b860939e399833bcacaa1f1a38b713029f8dc64

**Comment by GregoriusT** [comment]
Okay I will convert Grass Paths in a 3x3 Radius around the Players stepping on them instead of just doing a 1x1. This should fix "most" of the glitching through Floor Issue.

**Comment by GregoriusT** [comment]
by the way, the change you needed for the Water thing was adding 'mFlowsOnWater && ' to this:

`int tFlowMeta  = (mFlowsOnWater && aWorld.getBlock(aX, aY-densityDir, aZ) instanceof BlockWaterlike ? 1 : quantaPerBlock - quantaRemaining + 1);`

And ofcourse adding that variable itself and its Config assignment. ;)

**Comment by GregoriusT** [comment]
Okay that did somehow not work... I mustve made a mistake somewhere, but i will fix it within uhh a few hours i guess

**Comment by kappa-maintainer** [comment]
Now the river blocks seem working as intend, they do still flood caves but will no longer flood every cave in 10*10 chunks. As for the ocean block, some ignored logic somehow enabled them to create source blocks outside the ocean biome, which needs further fix.

**Comment by GregoriusT** [comment]
Are you sure it is not just the "2 sources create a third" mechanic working for oceans?

**Comment by kappa-maintainer** [comment]
![2022-03-29_20 46 15](https://user-images.githubusercontent.com/11038263/160614354-477a8006-bd98-4a3e-87cd-1c015ea2d931.png)
That's what I got when testing the new behavior, I have no idea how these source blocks were created in non-ocean biome

**Comment by kappa-maintainer** [comment]
Ocean block counts the bottom block when creating new sources, I guess that's why it can spread like the screenshot...
About the wetsuit, its texture can't fully cover player, so it does not in the HAZMATS list, which make sense. But the list itself have some problem: 1. It seems missing IC2's hazmat suit 2. Space suits should be able to protect players from chem gas and liquid too

**Comment by GregoriusT** [comment]
What Wet Suit? I never saw a Mod add that.

And IC2 Hazmat would be a bit OP if it did everything.

**Comment by kappa-maintainer** [comment]
Mariculture's wetsuit. I wanted to find a mod to both allow me to swim faster and avoid swamp water poison, but it turned out I can only choose one.

**Comment by kappa-maintainer** [comment]
The step logic got fixed in recent release of Et Futurum Requiem. Would you lower the height of grass path to 15/16 block?

**Comment by GregoriusT** [comment]
Here is the problem with that, my Path exists without Et Futurum too, and it has some different Features aswell (like turning into Slabs automatically). What purpose would having it 15/16ths tall even have?

Also if I remember correctly (correct me if I'm wrong), there still is the issue of not being able to go into a 2 block tall doorway when being on a slightly less tall Path Block (I remember that from Soulsand in ye olden days).

**Comment by kappa-maintainer** [comment]
The latest release of Et Futurum has fixed the step into 2 blocks tall space [problem](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/51) by mixin (tested), so I think adding a config of grass path height to fit actual model would be a good idea now
