### ISSUE TITLE
Fusion reactor skipping the LU charging process when restart the server

### ISSUE THREAD

**Issue by zhoule1217** [GregTech6/gregtech6#8]
Thermos server with GregTech 6.12.02. If restart the server when Fusion reactor is charging, it will immediately start to react process without enough LU.

**Comment by GregoriusT** [comment]
Could you elaborate on the "start to react process without enough LU" part? This could mean a whole range of different things depending on context and stuff.

**Comment by zhoule1217** [comment]
I hope to make Vibranium from Ad and Be-7, and NEI tells me it need 12 Billion LU to start the react. I use 8 Electric CO2 Lasers with power at 8192LU/t connected to the fusion reactor, and theoretically it needs 2.6 hours to finish the LU charging. However, only 10 minutes after the charging begin, I restart my server, and when I login again after the server online, the fusion reactor unexpectedly start to make Vibranium, just like "skip" the remaining process of LU charging. From the perspective of energy, I only spend about 1 Billion LU rather than 12 Billion to start the react.

**Comment by GregoriusT** [comment]
Are you sure it is 12 Billion and not 1.2 Billion?

**Comment by OvermindDL1** [comment]
Looks like the recipe is defined at:
https://github.com/GregTech6/gregtech6/blob/master/src/main/java/gregtech/loaders/c/Loader_Recipes_Other.java#L840

```java
RM.Fusion.addRecipe1(F, -8192, 1956, ST.tag(2), FL.array(MT.Ad    .liquid(U  , T), MT.Be_7.liquid(U  , T)), FL.array(MT.W     .liquid(  U , F), MT.He    .gas   (16*U, F), MT.He_3  .gas   (24*U, F), MT.T     .gas   (24*U, F)), OP.dust.mat(MT.Vb, 1)).setSpecialNumber(94956L*8192L*16L);
```
So it looks like it gives 8192 EU, takes 1956, input is Ad and Be7 fluids and outputs W (tungsten right?), He3, and T fluids as well as Vb dust.  Then it sets the special number of `94956L*8192L*16L`, which is `12446072832`, which with commas is `12,446,072,832`, so it looks like it should take 12.45 billion to start?  Unless there is a division by 10 somewhere?

**Comment by OvermindDL1** [comment]
On https://github.com/GregTech6/gregtech6/blob/master/src/main/java/gregapi/tileentity/machines/MultiTileEntityBasicMachine.java#L734 it is just:
```java
if (mSpecialIsStartEnergy && (!mActive || (mCurrentRecipe != null && mCurrentRecipe != tRecipe))) mChargeRequirement = tRecipe.mSpecialValue;
```
So it is just dumped straight into `mChargeRequirement`, and looking around at it I don't see it being set except to 0 in some cases and by `mChargeRequirement--` and `mChargeRequirement -= aSize * aAmount` in some other cases in all the source.

**Comment by zhoule1217** [comment]
"Are you sure it is 12 Billion and not 1.2 Billion?". Of course I am. I did further test and found that it would totally skip current LU charging whenever I restart my server, even if I didn't turn on any one of my Electric CO2 Lasers. I guess that the current state of "how many LU have been input" have not been saved when world is saved.

**Comment by zhoule1217** [comment]
So, a funny thing is that I only need to restart my server rather than input huge amount of LU to start the react...

**Comment by GregoriusT** [comment]
Okay,I thought I did make sure the Power Requirement was saved in NBT, guess it is not for some reason.

**Comment by GregoriusT** [comment]
Found and fixed the Issue. Using an 8 Bit Byte to store a 64 Bit Long is not a good Idea. XD
