### ISSUE TITLE
How to generate ore layer in galaxyspace

### ISSUE THREAD

**Issue by NaCl0526** [GregTech6/gregtech6#87]
I tried
![image](https://user-images.githubusercontent.com/62875887/174719526-dda97dd7-129b-47fa-9bcb-6657f7daa573.png)

But he doesn't work
It seems to be an ore without corresponding material

**Comment by GregoriusT** [comment]
Uhhh try reading this Thread, maybe it helps;

https://forum.mechaenetia.com/t/galaxyspace-ore-generation-please-help/2278

**Comment by TheOnlySakura** [comment]
I seem to understand
The reason why there is no ore layer is that there is no stone
I just need to register the planet rock as a kind of stone, and then configure stonelayers to generate orelayer?

**Comment by GregoriusT** [comment]
Maybe that works, but I'm not sure.

**Comment by GregoriusT** [comment]
Uh, I am not sure how well that works if there is not even MercuryRock Dust?

**Comment by NaCl0526** [comment]
![image](https://user-images.githubusercontent.com/62875887/175517489-f53b2c9c-9994-4154-aef7-b39a7c135b39.png)

Successfully generated ore

**Comment by GregoriusT** [comment]
Yay, so I can close this Issue then.
