### ISSUE TITLE
Breeder rod is not working

### ISSUE THREAD

**Issue by stsouko** [GregTech6/gregtech6#99]
I tried the following schema:

```
    R
R Pu R
R Pu U
R Pu R
    R
```
Pu 241
R - reflector
U 238 breeding rod
neutrons count on Pu 4500+

**Comment by GregoriusT** [comment]
I will summon @Erik3003 for this since he knows this System better, considering he made it.

**Comment by Erik3003** [comment]
Not a bug. U238 breeder rods have a neutron loss of 2500 Neutrons and the setup (which seems to be using Industrial Coolant to get those neutron counts on the Pu) only outputs ~1000 neutrons onto it, which means no neutrons remain to go towards the breeding process.

To breed U238 into Pu239, Neutron outputs greater than 2500 neutrons are needed, preferably something like 5000 neutrons or even greater. This in turn means neutron counts of at least 10000 neutrons on the adjacent fuel rod are needed, something which is only realistically achievable with supercritical reactors using coolants other than Industrial Coolants (or water based coolants, as these prohibit breeding by moderating the fuel rods).

**Comment by stsouko** [comment]
Ok. Thank you for explanation.
